### ISSUE TITLE
Introduce flow for when a user is not currently streaming.

### ISSUE THREAD

**Issue by victorwrotethis** [vduits/streamer-endpoints#10]
Currently when a user is not streaming it will generate errors. The endpoints should provide clear error messages to the end-user.

**Comment by davidwisniowski** [comment]
hey. for that case i would throw a TwitchApiException with the specific message (e.g. "The User with ID {id} is not streaming currently" and print a clear message to the user as string. 

method: retrieveStreamByUserId

if it's ok just assign it to me.
