### ISSUE TITLE
Make docker-compose production ready

### ISSUE THREAD

**Issue by victorwrotethis** [vduits/streamer-endpoints#2]
- [ ] Move current docker-compose file to deployment/local folder
- [ ] Create a deployment/prod folder containing a new compose file that uses env vars for the database
- [ ] Map docker volume for db data (preferably using new mount syntax)
- [ ] Add the application itself as a service to prod docker-compose and make a path to the Dockerfile

**Comment by MgBacon** [comment]
ayo o7

**Comment by victorwrotethis** [comment]
It is relevant again. Thanks for picking it up.
