### ISSUE TITLE
Extract common api call behaviour

### ISSUE THREAD

**Issue by victorwrotethis** [vduits/streamer-endpoints#7]
With adding the IGDB API in sight we want to extract common api call behaviour into a new class. There are some similarities with twitch, but the rate limit system works differently and its ties should be omitted where possible. 

- [x] Create new service for the connection handling for both twitch/igdb with a good name.
- [x] Extract buildconnection, addHeaders and readresponse from TwitchApi.
- [x] Extract the twitch ratelimit parts from readresponse, for example by returning a new pojo with the body and headers that the higher level service can work with (in this case TwitchApi.request)

**Comment by PS2emu** [comment]
I can complete this issue by mid-to-late week.

**Comment by victorwrotethis** [comment]
Alright good luck, let me know if you have any questions.

**Comment by victorwrotethis** [comment]
Thanks for helping out.
