### ISSUE TITLE
Create new service that can communicate with IGDB

### ISSUE THREAD

**Issue by victorwrotethis** [vduits/streamer-endpoints#8]
The next step to integrating IGDB game information is to create services related to calling that api. The first one is using the [external game endpoint](https://api-docs.igdb.com/?java#external-game). Using the following syntax you can retrieve the IGDB id for Fortnite using the twitch version of the game id.
```
fields game,name;
where uid = "33214" & category = 14; 
```

- [x] Create new IGDB package containing a IGDBAPI service (or perhaps a better name) that is used to perform requests
- [x] Create IGDBGameService that performs the detailed calls through the previous API service
- [x] Add method to call `external_game`  to match the twitch game-id with the IGDB one.
- [x] Add method to call `game` to retrieve the summary and url. 
- [x] Create enums for the IGDB endpoints
- [x] Create an enum for the allowed fields used per igdb endpoint. Meaning only `summary` and `url` at this point for the `game`

**Comment by PS2emu** [comment]
I can easily milk 3 more PR's from this one issue :P
